"""Thermodynamic probabilistic computing emulator."""

__version__ = "0.1.0"

from .config import (
    DeviceConfig,
    PhysicalTimeReport,
    ThermodynamicNeuronConfig,
    ThermodynamicTransformerConfig,
    set_seed,
)
from .cnn import (
    CNNFitResult,
    CNNReadoutFitResult,
    ThermodynamicCNNClassifier,
    ThermodynamicConv2d,
    accuracy,
    fit_cnn_classifier,
    fit_cnn_classifier_end_to_end,
    fit_cnn_readout_ridge,
    make_toy_cnn_data,
)
from .distributions import (
    DistributionAdapter,
    DistributionSampler,
    DistributionSpec,
    available_distributions,
    distribution_class,
    make_distribution,
    sample_distribution,
)
from .flow_matching import (
    FlowMatchFitResult,
    FlowReadoutFitResult,
    FlowSampleResult,
    FlowVelocityMLP,
    ThermodynamicFlowVelocity,
    fit_flow_matching,
    fit_flow_matching_end_to_end,
    fit_flow_matching_readout_ridge,
    flow_matching_loss,
    flow_matching_pair_loss,
    flow_speedup_vs_diffusion,
    make_mog2d,
    rbf_mmd2,
    sample_flow,
    time_embedding,
)
from .integration import ThermodynamicFFN, ThermodynamicTransformerBlock, replace_ffn
from .metrics import ExperimentResult, moment_summary, physical_advantage_ratio
from .memory import (
    FFNMemoryEstimate,
    estimate_classical_ffn_memory,
    estimate_thermo_ffn_memory,
)
from .precision import (
    NumericFormatSpec,
    QuantizationConfig,
    QuantizedFFNMemoryEstimate,
    QuantizedFitResult,
    QuantizedThermodynamicFFN,
    available_numeric_formats,
    estimate_quantized_thermo_ffn_memory,
    fit_quantized_ffn_mse,
    get_numeric_format,
    numeric_format_bits,
    quantize_tensor,
    quantized_storage_nbytes,
)
from .neurons import (
    ThermodynamicMLP,
    ThermodynamicNeuronLayer,
    ThermodynamicRunInfo,
    quartic_potential,
)
from .transformer import (
    ThermodynamicSelfAttention,
    ThermodynamicTransformerInfo,
    ThermodynamicTransformerLayer,
)
from .training import (
    ColdEndToEndFitResult,
    ParallelTemperedEndToEndFitResult,
    ParallelTemperedMaskFitResult,
    ReadoutFitResult,
    fit_transformer_end_to_end_cold,
    fit_transformer_end_to_end_parallel_tempering,
    fit_transformer_readout_parallel_tempering,
    fit_transformer_readout_ridge,
)
from .superiority_demo import run_superiority_demo
from .primitives import (
    BinaryPBit,
    CategoricalPDIT,
    IsingEnergy,
    PMODE,
    PMOG,
)

__all__ = [
    "BinaryPBit",
    "CNNFitResult",
    "CNNReadoutFitResult",
    "CategoricalPDIT",
    "DeviceConfig",
    "DistributionAdapter",
    "DistributionSampler",
    "DistributionSpec",
    "ExperimentResult",
    "FFNMemoryEstimate",
    "FlowMatchFitResult",
    "FlowReadoutFitResult",
    "FlowSampleResult",
    "FlowVelocityMLP",
    "IsingEnergy",
    "PhysicalTimeReport",
    "PMODE",
    "PMOG",
    "NumericFormatSpec",
    "QuantizationConfig",
    "QuantizedFFNMemoryEstimate",
    "QuantizedFitResult",
    "QuantizedThermodynamicFFN",
    "ThermodynamicMLP",
    "ThermodynamicCNNClassifier",
    "ThermodynamicConv2d",
    "ThermodynamicFlowVelocity",
    "ThermodynamicNeuronLayer",
    "ThermodynamicNeuronConfig",
    "ThermodynamicRunInfo",
    "ThermodynamicSelfAttention",
    "ThermodynamicFFN",
    "ThermodynamicTransformerBlock",
    "ThermodynamicTransformerConfig",
    "ThermodynamicTransformerInfo",
    "ThermodynamicTransformerLayer",
    "ColdEndToEndFitResult",
    "ParallelTemperedEndToEndFitResult",
    "ParallelTemperedMaskFitResult",
    "ReadoutFitResult",
    "fit_transformer_end_to_end_cold",
    "fit_transformer_end_to_end_parallel_tempering",
    "fit_transformer_readout_parallel_tempering",
    "fit_transformer_readout_ridge",
    "fit_cnn_classifier",
    "fit_cnn_classifier_end_to_end",
    "fit_cnn_readout_ridge",
    "fit_flow_matching",
    "fit_flow_matching_end_to_end",
    "fit_flow_matching_readout_ridge",
    "flow_matching_loss",
    "flow_matching_pair_loss",
    "flow_speedup_vs_diffusion",
    "available_distributions",
    "available_numeric_formats",
    "accuracy",
    "distribution_class",
    "estimate_quantized_thermo_ffn_memory",
    "estimate_classical_ffn_memory",
    "estimate_thermo_ffn_memory",
    "fit_quantized_ffn_mse",
    "get_numeric_format",
    "make_distribution",
    "make_mog2d",
    "make_toy_cnn_data",
    "moment_summary",
    "numeric_format_bits",
    "physical_advantage_ratio",
    "quartic_potential",
    "quantize_tensor",
    "quantized_storage_nbytes",
    "replace_ffn",
    "rbf_mmd2",
    "run_superiority_demo",
    "sample_distribution",
    "sample_flow",
    "set_seed",
    "time_embedding",
]
